name: ROS2 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build on ROS2 ${{ matrix.ros_distro }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [ humble, iron ]
        include:
          - ros_distro: 'humble'
            os: ubuntu-22.04
          - ros_distro: 'iron'
            os: ubuntu-22.04

    steps:
      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distro }}

      - name: Setup ROS2 workspace
        run: |
          source /opt/ros/${{ matrix.ros_distro }}/setup.bash
          mkdir -p ${{github.workspace}}/ros2_ws/src
          cd ${{github.workspace}}/ros2_ws
          colcon build

      - name: Checkout ROSplane
        uses: actions/checkout@v3
        with:
          path: 'ros2_ws/src/rosplane'

      - name: Checkout rosflight_msgs
        uses: actions/checkout@v4
        with:
          repository: rosflight/rosflight
          path: 'ros2_ws/src/rosflight'
          sparse-checkout: |
            rosflight_msgs
          sparse-checkout-cone-mode: false

      - name: Install dependencies
        run: |
          cd ${{github.workspace}}/ros2_ws
          rosdep update
          rosdep install --from-paths ./ -i -y -r --rosdistro ${{ matrix.ros_distro }}

      - name: Build ROSplane
        run: |
          source /opt/ros/${{ matrix.ros_distro }}/setup.bash
          cd ${{github.workspace}}/ros2_ws
          colcon build --event-handlers console_direct+
